# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

os: 
  - osx
  
sudo: true
cache: packages

r:
- devel

before_script:
- java -version
- echo PATH=$PATH
- echo JAVA_HOME=$JAVA_HOME
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo R CMD javareconf ; fi
